package de.chw.sdg.db;

import org.neo4j.graphdb.RelationshipType;

public enum RelTypes implements RelationshipType {
	CONTROL_FLOW, DATA_FLOW,
	AGGR_CTRL_FLOW,
	CONTAINS_PACKAGE, CONTAINS_TYPE, CONTAINS_FIELD, CONTAINS_METHOD, CONTAINS_CONSTRUCTOR, CONTAINS_UNIT, LAST_UNIT,
	CALLS,
	IS, CALLER_OF, AGGREGATED_CALLS,
	EXTENDS, IMPLEMENTS,
	AGGREGATED_FIELD_READ, AGGREGATED_FIELD_WRITE, THROWS,

	REFERS_TO,
}
